export const POSTS_FETCH_ONE_SUCCESS = 'posts.POSTS_FETCH_ONE_SUCCESS';
export const POSTS_FETCH_SUCCESS = 'posts.POSTS_FETCH_SUCCESS';
export const POSTS_CREATE_SUCCESS = 'posts.POSTS_CREATE_SUCCESS';
export const POSTS_UPDATE_SUCCESS = 'posts.POSTS_UPDATE_SUCCESS';
export const POSTS_DELETE_SUCCESS = 'posts.POSTS_DELETE_SUCCESS';
