export const CATEGORIES_FETCH_ONE_SUCCESS = 'categories.CATEGORIES_FETCH_ONE_SUCCESS';
export const CATEGORIES_FETCH_SUCCESS = 'categories.CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_CREATE_SUCCESS = 'categories.CATEGORIES_CREATE_SUCCESS';
export const CATEGORIES_UPDATE_SUCCESS = 'categories.CATEGORIES_UPDATE_SUCCESS';
export const CATEGORIES_DELETE_SUCCESS = 'categories.CATEGORIES_DELETE_SUCCESS';
